[Variables]

userinfoX=145
userinfoY=120

noteX=145
noteY=490

petalsX=475
petalsY=125

appsX=475
appsY=305

storageX=475
storageY=490

foldersX=660
foldersY=125

mailX=660
mailY=480

calendarX=905
calendarY=125

uptimeX=905
uptimeY=570

bgRadius=15

dashBgBlur=1
dashBgColor=255,255,255,5

bgAlpha=255
bgColorD=26,32,38
bgColorL=30,37,44
bgColorS=45,54,63
fgColorL=245,245,245
fgColorD=85,100,116

pink=251,99,150
indigo=106,186,206
cyan=127,228,210
blue=100,183,214
violet=194,105,188
green=148,207,149
peach=246,146,178

gsans=Google Sans
sfdisp=SF UI Display
iosevka=Iosevka Custom
jbmono=JetBrains Mono

plugin=WebNowPlaying
player=spotify

disableMode=!DeactivateConfig
dashLaunchKey=LWIN Z

userName=[UserAccountName]
setupName=lovelace

p1Name=GH
p2Name=YT
p3Name=RD
p4Name=DA
p1path=https://github.com/
p2path=https://www.youtube.com/
p3path=https://www.reddit.com/
p4path=https://www.deviantart.com/

app1Icon=#@#Icons\browser.png
app2Icon=#@#Icons\discord.png
app1Path=C:\Program Files\Mozilla Firefox\firefox.exe
app2Path=%AppData%\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk

folder1=home
folder2=downloads
folder3=music
folder4=pictures
folder5=wallpapers
folder6=screenshots
folder1Path=Shell:MyComputerFolder
folder2Path=Shell:Downloads
folder3Path=Shell:My Music
folder4Path=Shell:My Pictures
folder5Path=Shell:Downloads\Wallpapers
folder6Path=Shell:My Pictures\Screenshots

unreadCount=0
title1=
title2=
title3=
link1=
link2=
link3=
author1=
author2=
author3=

path1=%AppData%\Spotify\Spotify.exe 
ititle1=
;Spotify
process1=Spotify.exe

path2=C:\Program Files\Mozilla Firefox\firefox.exe
ititle2=firefox
process2=firefox.exe

path3=C:\Users\%UserName%\AppData\Local\Discord\Update.exe --processStart Discord.exe
ititle3=
;Discord
process3=Discord.exe

path4=C:\Users\%UserName%\AppData\Local\Programs\Microsoft VS Code\Code.exe
ititle4=Visual Studio Code
process4=Code.exe

path5=
ititle5=
process5=

path6=
ititle6=
process6=

currentVersion=1.0
discAv=1
avatar=C:\Users\hp\Documents\Rainmeter\Skins\Lovelace\Dashboard\DownloadFile\dAvatar.png
avatarPath=#@#Images\defaultAvImg.jpeg
avatarLink=#RootConfigPath#Dashboard\DownloadFile\dAvatar.png
currentPage=1
animSmooth=1
visSmooth=0
tFormat=12
powerMenu=1
noteSize=11
mainNoteColor=indigo

gmailUser=example69
gmailPass=blahblah420

[UserAccountName]
Measure=Plugin
Plugin=SysInfo
SysInfoType=User_Name
Substitute="hp":"Modka"
